export const ADD_TO_CART = 'ADD_TO_CART';
export const INCREASE_QUANTITY = 'INCREASE_QUANTITY';
export const DECREASE_QUANTITY = 'DECREASE_QUANTITY';
export const CALCULATE_TOTAL_PRICE = 'CALCULATE_TOTAL_PRICE';
export const SEARCH_PRODUCT_LISTING = 'SEARCH_PRODUCT_LISTING';
export const ALL_PRODUCT_LISTING = 'ALL_PRODUCT_LISTING';
